import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Navbar from "../components/Navbar";

export default function Home() {
    return (
        <App>
            <Head>
                <title>Whats Up</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
        </App>
    );
}

const App = styled.main``;
